[Basic]
random_seed = 0
cuda_id     = 0

base_path   = "../models/final-test"
folder_name = "crf-upos-ud"

[Corpus]
tag_type = "upos"

    [Corpus.UD_ENGLISH]

[Embeddings]

    [Embeddings.OneHotEmbeddings]
    embedding_length = 256
    min_freq         = 1

[SequenceTagger]
tagger           = "CustomSequenceTagger"

    [SequenceTagger.module]
    name             = "HalfLazyHeadProbEncoder"
    d_model          = 256
    n_head           = 8
    n_iter           = 6
    damping_H        = 0
    damping_Z        = 0
    stepsize_H       = 0.8
    stepsize_Z       = 0.5
    regularize_H     = 1
    regularize_Z     = 1
    dists            = "2, 3, 4"
    async_update     = true
    use_td           = "no"
    dropout          = 0.15
    block_msg        = false

[Trainer]
trainer              = "CustomModelTrainer"
learning_rate        = 0.0087
mini_batch_size      = 64
mini_batch_chunk_size= 16
max_epochs           = 100
shuffle              = true
eps                  = 1e-9
weight_decay         = 4.4e-6

anneal_factor        = 0.5
patience             = 5
min_learning_rate    = 0.0000001

embeddings_storage_mode = 'none'
