[Basic]
random_seed = 0
cuda_id     = 0

base_path   = "../models/final-test"
folder_name = "crf-syn-cogs"

[Corpus]
tag_type = "pos"

    [Corpus.COGS_SequenceLabeling]
    mapping = 'relative'
    test_split = 'gen'

[Embeddings]

    [Embeddings.OneHotEmbeddings]
    embedding_length = 64
    min_freq         = 1

[SequenceTagger]
tagger           = "MultiLabelSequenceTagger"

    [SequenceTagger.module]
    name             = "HalfLazyHeadProbEncoder"
    d_model          = 64
    n_head           = 4
    n_iter           = 2
    damping_H        = 0
    damping_Z        = 0
    stepsize_H       = 1
    stepsize_Z       = 1
    regularize_H     = 1
    regularize_Z     = 1
    dists            = "2, 3, 4, 5, 6, 7, 8, 9"
    async_update     = true
    use_td           = "uv:16"
    dropout          = 0.1
    block_msg        = false

[Trainer]
trainer              = "CustomModelTrainer"
learning_rate        = 0.0025
mini_batch_size      = 100
mini_batch_chunk_size= 100
max_epochs           = 200
shuffle              = true
eps                  = 1e-9

anneal_factor        = 0.5
patience             = 5
min_learning_rate    = 0.0000001

embeddings_storage_mode = 'none'
