[Basic]
random_seed = 0
cuda_id     = 0

base_path   = "../models/final-test"
folder_name = "crf-pos-ptb"

[Corpus]
tag_type = "pos"

    [Corpus.PennTreebankCorpus]
    splits = "0-18|19-21|22-24"

[Embeddings]

    [Embeddings.OneHotEmbeddings]
    embedding_length = 128
    min_freq         = 1

[SequenceTagger]
tagger           = "CustomSequenceTagger"

    [SequenceTagger.module]
    name             = "HalfLazyHeadProbEncoder"
    d_model          = 128
    n_head           = 12
    n_iter           = 3
    damping_H        = 0
    damping_Z        = 0
    stepsize_H       = 1
    stepsize_Z       = 1
    regularize_H     = 1
    regularize_Z     = 1
    dists            = "2, 3, 4"
    async_update     = true
    use_td           = "uv:128"
    dropout          = 0.05
    block_msg        = false

[Trainer]
trainer              = "CustomModelTrainer"
learning_rate        = 0.0024
mini_batch_size      = 16
mini_batch_chunk_size= 16
max_epochs           = 100
shuffle              = true
eps                  = 1e-9
weight_decay         = 8e-6

anneal_factor        = 0.5
patience             = 5
min_learning_rate    = 0.0000001

embeddings_storage_mode = 'none'
