[Basic]
random_seed = 0
cuda_id     = 0

base_path   = "../models/final-test"
folder_name = "transformer-cls-sst2"

[Corpus]
tag_type = "class"

    [Corpus.SENTEVAL_SST_BINARY]

[Embeddings]

    [Embeddings.OneHotEmbeddings]
    embedding_length = 256
    min_freq         = 1

[SequenceTagger]
tagger           = "CustomTextClassifier"
add_cls          = true

    [SequenceTagger.module]
    name             = "TransformerEncoder"
    d_model          = 256
    d_ff             = 512
    n_layers         = 8
    n_head           = 10
    d_qkv            = 256
    dropout          = 0.05
    pos_embed        = "add"


[Trainer]
trainer              = "CustomModelTrainer"
learning_rate        = 0.0001
mini_batch_size      = 128
max_epochs           = 100
shuffle              = true
eps                  = 1e-9
weight_decay         = 1.9e-6

anneal_factor        = 0.5
patience             = 5
min_learning_rate    = 0.0000001

embeddings_storage_mode = 'none'
