[Basic]
random_seed = 0
cuda_id     = 0

base_path   = "../models/final-test"
folder_name = "transformer-ner-conll03"

[Corpus]
tag_type = "ner"

    [Corpus.AUTO_CONLL_03]

[Embeddings]

    [Embeddings.OneHotEmbeddings]
    embedding_length = 256
    min_freq         = 1

[SequenceTagger]
tagger           = "CustomSequenceTagger"

    [SequenceTagger.module]
    name             = "TransformerEncoder"
    d_model          = 256
    d_ff             = 512
    n_layers         = 3
    n_head           = 16
    d_qkv            = 16
    dropout          = 0.05
    pos_embed        = "add"

[Trainer]
trainer              = "CustomModelTrainer"
learning_rate        = 0.0007
mini_batch_size      = 32
max_epochs           = 100
shuffle              = true
eps                  = 1e-9
weight_decay         = 5.5e-7

anneal_factor        = 0.5
patience             = 5
min_learning_rate    = 0.0000001

embeddings_storage_mode = 'none'